# Generated by Django 5.2.1 on 2025-05-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalImunisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_anak', models.CharField(max_length=100)),
                ('jenis_imunisasi', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('selesai', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_imunisasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
